version: '3.8'
services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: loganlee
            POSTGRES_PASSWORD: dkffkel
            POSTGRES_DB: stastica
        ports:
            - 5432:5432
        volumes:
            - /Users/loganlee/project/docker/postgres:/var/lib/postgresql/data
    front:
        image: loganlee/stastica_front
        container_name: front
        stdin_open: true
        tty: true
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_SERVER_URL=http://back:3333
        command: ['yarn', 'start']
    back:
        image: loganlee/stastica_back
        container_name: back
        depends_on:
            - postgres
        stdin_open: true
        tty: true
        ports:
            - 3333:3333
        environment:
            - CHOKIDAR_USEPOLLING=true
            - DATABASE_URL=postgresql://loganlee:dkffkel@postgres:5432/stastica?schema=stastica
        # command: ['yarn', 'start']
